apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deployment
  labels:
    app: runner-deployment
  namespace: runner
spec:
  selector:
    matchLabels:
      app: runner-deployment
  template:
    metadata:
      labels:
        app: runner-deployment
        date: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: starvation-runner
      containers:
        - name: runner
          {{- if .Values.local }}
          image: bbcs/runner
          imagePullPolicy: Never
          {{- else }}
          image: asia-southeast1-docker.pkg.dev/starvation/docker/runner:latest
          imagePullPolicy: Always
          {{- end }}
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: host
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: database
