apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-pods-admin
  namespace: sandbox
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]