apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-pods-admin-binding
  namespace: sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sandbox-pods-admin
subjects:
  - kind: ServiceAccount
    name: starvation-runner
    namespace: runner
  - kind: ServiceAccount
    name: starvation-server
    namespace: server