apiVersion: v1

kind: Service

metadata:
  name: server-service
  namespace: server
  cloud.google.com/backend-config: '{"default": "server-backendconfig"}'

spec:
  type: LoadBalancer
  selector:
    app: server-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
