apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-deployment
  namespace: server
spec:
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
        date: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: starvation-server
      containers:
        - name: server
          {{- if .Values.local }}
          image: bbcs/server
          imagePullPolicy: Never
          {{- else }}
          image: asia-southeast1-docker.pkg.dev/starvation/docker/server:latest
          imagePullPolicy: Always
          {{- end }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m" 
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: host
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: database
