apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-deployment
  namespace: server
spec:
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
        date: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: bbcs-server
      containers:
        - name: server
          image: asia-southeast1-docker.pkg.dev/starvation/docker/server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m" 
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-host
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: database
