apiVersion: v1
kind: Pod
metadata:
  name: sandbox
spec:
  containers:
    - name: sandbox
      image: bbcs/sandbox
      imagePullPolicy: Never
      resources:
        limits:
          memory: "64Mi"
          cpu: "100m"
  restartPolicy: Never
  
