apiVersion: v1
kind: Pod
metadata:
  name: sandbox
spec:
  containers:
    - name: sandbox
      image: asia-southeast1-docker.pkg.dev/starvation/docker/sandbox:latest
      imagePullPolicy: Always
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
  restartPolicy: Never
  
