apiVersion: v1
kind: Pod
metadata:
  name: sandbox
spec:
  containers:
    - name: sandbox
      # image: bbcs/sandbox
      # imagePullPolicy: Never
      image: asia-southeast1-docker.pkg.dev/starvation/docker/sandbox:latest
      imagePullPolicy: Always
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
  restartPolicy: Never
  
