name: Deploy to Google Cloud

on:
  workflow_dispatch:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: "projects/596255395612/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions-provider"
        service_account: "github-actions@starvation.iam.gserviceaccount.com"

    - uses: 'docker/login-action@v1'
      name: 'Login to Google Artifact Registry'
      with:
        registry: 'asia-southeast1-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: 'Build and push server'
      uses: 'docker/build-push-action@v4'
      with:
        file: ./server/Dockerfile
        push: true
        tags: bbcs/server:latest

    - name: 'Build and push sandbox'
      uses: 'docker/build-push-action@v4'
      with:
        file: ./simulator/Dockerfile
        push: true
        tags: bbcs/sandbox:latest

